// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQD_ChARZnQzs-dQTzCus7m7HeTyrLC9c',
    appId: '1:419112463001:web:4f4a9a8fe5886d673f2608',
    messagingSenderId: '419112463001',
    projectId: 'train-app-b3cbd',
    authDomain: 'train-app-b3cbd.firebaseapp.com',
    storageBucket: 'train-app-b3cbd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1GkNNkFKL2b72bCxTDPHXlkYspZLcw9M',
    appId: '1:419112463001:android:99789435086735b03f2608',
    messagingSenderId: '419112463001',
    projectId: 'train-app-b3cbd',
    storageBucket: 'train-app-b3cbd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAS5F7PdfYL5onIw8TrAvdLT6KLy6_pdcQ',
    appId: '1:419112463001:ios:de29eff4a92287e63f2608',
    messagingSenderId: '419112463001',
    projectId: 'train-app-b3cbd',
    storageBucket: 'train-app-b3cbd.appspot.com',
    iosClientId: '419112463001-e9do8fl6qp5j3u4flrmb7qh93eel5oul.apps.googleusercontent.com',
    iosBundleId: 'com.example.trainApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAS5F7PdfYL5onIw8TrAvdLT6KLy6_pdcQ',
    appId: '1:419112463001:ios:de29eff4a92287e63f2608',
    messagingSenderId: '419112463001',
    projectId: 'train-app-b3cbd',
    storageBucket: 'train-app-b3cbd.appspot.com',
    iosClientId: '419112463001-e9do8fl6qp5j3u4flrmb7qh93eel5oul.apps.googleusercontent.com',
    iosBundleId: 'com.example.trainApp',
  );
}
